export const demos={
  "nexus-bridge":{name:"Nexus Bridge",eyebrow:"Produto SaaS · integração de sistemas",title:"O legado continua funcionando. O negócio começa a fluir.",summary:"Uma camada de integração para empresas que precisam receber, transformar, validar e entregar dados entre sistemas sem uma migração arriscada de uma só vez.",metric:"12.840",metricLabel:"eventos processados no ambiente demo",primary:"Fluxo validado e em execução",secondary:"1 destino aguardando configuração",items:["Aplicação legada recebe o pedido","Sandbox valida e transforma o dado","API entrega no destino escolhido"],accent:"emerald",pill:"n8n · Apache Airflow · APIs · sandbox"},
  "fiscal-connect":{name:"Fiscal Connect",eyebrow:"Produto SaaS · automação fiscal",title:"Nota fiscal conectada à sua operação, sem planilha no caminho.",summary:"Uma automação segura para capturar documentos fiscais, validar informações e disponibilizar os dados para ERP, financeiro, estoque ou qualquer aplicação do cliente.",metric:"99,9%",metricLabel:"documentos validados no ambiente demo",primary:"Documento fiscal processado",secondary:"2 documentos precisam de conferência",items:["Documento recebido por fonte autorizada","Regras validam campos e consistência","Dados entregues ao ERP ou à sua API"],accent:"sky",pill:"NF-e · regras fiscais · ERP · webhooks"},
  "ia-de-negocio":{name:"Context AI",eyebrow:"Produto SaaS · inteligência artificial aplicada",title:"IA que conhece o contexto do negócio e ajuda a operação a decidir.",summary:"Assistentes e automações que usam os dados, processos e linguagem da sua empresa para atender, classificar, resumir, analisar e executar tarefas com controle humano.",metric:"24",metricLabel:"tarefas assistidas no ambiente demo",primary:"Assistente pronto para revisão",secondary:"3 decisões aguardam aprovação humana",items:["Fontes internas organizam o contexto","IA classifica, resume ou recomenda","Pessoa aprova e o fluxo executa a ação"],accent:"amber",pill:"RAG · agentes · aprovação humana · auditoria"}
  ,"operacoes-dados":{name:"Pulse Ops",eyebrow:"Aplicação sob medida · operações e dados",title:"A operação inteira em uma tela que dá para agir.",summary:"Um painel de exceções para equipes que precisam cruzar receita, pedidos e integrações antes que um desvio vire atraso.",metric:"R$ 184 mil",metricLabel:"receita sob monitoramento",primary:"Integrações saudáveis",secondary:"3 exceções pedem atenção",items:["Pedidos aguardando conciliação","Fila de importação ERP","Sincronização do catálogo"],accent:"emerald",pill:"Dashboards · alertas · ERP · dados operacionais"}
  ,"automacao-conversacional":{name:"Fluxo Inbox",eyebrow:"Aplicação sob medida · automação conversacional",title:"Cada conversa chega com contexto para a próxima decisão.",summary:"Uma central para triagem, qualificação e continuidade de atendimentos que passam por WhatsApp, automações e equipe humana.",metric:"42",metricLabel:"conversas qualificadas hoje",primary:"Automação em execução",secondary:"6 conversas aguardam pessoa",items:["Novo lead: indústria de alimentos","Pagamento confirmado","Solicitação de proposta"],accent:"sky",pill:"WhatsApp · n8n · CRM · atendimento humano"}
  ,"telemetria-industrial":{name:"Linha Sinal",eyebrow:"Aplicação sob medida · monitoramento industrial",title:"Sinais da fábrica antes que virem parada.",summary:"Uma leitura operacional de ativos conectados, desenhada para tornar alarmes, tendência e intervenção compreensíveis em segundos.",metric:"98,7%",metricLabel:"disponibilidade da linha",primary:"Linha em produção",secondary:"1 manutenção programada",items:["Prensa 03 · temperatura estável","Esteira 02 · velocidade nominal","Sensor de vibração · inspeção"],accent:"amber",pill:"Modbus · Profinet · SCADA · telemetria"}
  ,"desktop-critico":{name:"Station Control",eyebrow:"Aplicação sob medida · desktop",title:"Software local quando estabilidade e resposta são inegociáveis.",summary:"Uma aplicação desktop para operações que precisam continuar funcionando perto do processo, com interface rápida e integração aos equipamentos e dados locais.",metric:"< 80 ms",metricLabel:"resposta local no ambiente demo",primary:"Estação conectada",secondary:"Sincronização programada para a nuvem",items:["Operador registra a operação local","Regras validam os dados na estação","Sincronização envia eventos ao servidor"],accent:"emerald",pill:"Tauri · Rust · React · operação offline"}
} as const;
export type DemoSlug=keyof typeof demos;
export function isDemoSlug(value:string):value is DemoSlug{return value in demos;}
